import type { PerformanceSnapshot } from '@ai-telemetry-toolkit/core';

export function generatePrSummary(
  before: PerformanceSnapshot,
  after: PerformanceSnapshot,
): string {
  const lines: string[] = [
    `## Performance Analysis`,
    ``,
    `> Generated by [ai-telemetry-toolkit](https://github.com/matiaspautasso/ai-telemetry-toolkit)`,
    ``,
  ];

  const beforeAvg =
    before.backendMetrics.length > 0
      ? before.backendMetrics.reduce((s, m) => s + m.durationMs, 0) / before.backendMetrics.length
      : 0;
  const afterAvg =
    after.backendMetrics.length > 0
      ? after.backendMetrics.reduce((s, m) => s + m.durationMs, 0) / after.backendMetrics.length
      : 0;

  const delta = afterAvg - beforeAvg;
  const pct = beforeAvg > 0 ? Math.round((delta / beforeAvg) * 100) : 0;
  const icon = delta < 0 ? '✅' : delta > 0 ? '⚠️' : '➡️';

  lines.push(`### Response Time`);
  lines.push(`| | Before | After | Change |`);
  lines.push(`|-|--------|-------|--------|`);
  lines.push(
    `| Avg | ${Math.round(beforeAvg)}ms | ${Math.round(afterAvg)}ms | ${icon} ${pct > 0 ? '+' : ''}${pct}% |`,
  );
  lines.push(``);

  if (after.findings.length > 0) {
    lines.push(`### Findings`);
    after.findings.forEach((f) => {
      lines.push(`- **${f.severity.toUpperCase()}**: ${f.title} — ${f.evidence}`);
    });
    lines.push(``);
  }

  return lines.join('\n');
}

export function generateSinglePrSummary(snapshot: PerformanceSnapshot): string {
  const lines: string[] = [
    `## Performance Snapshot`,
    ``,
    `> Generated by [ai-telemetry-toolkit](https://github.com/matiaspautasso/ai-telemetry-toolkit)`,
    ``,
  ];

  const slowCount = snapshot.backendMetrics.filter((m) => m.durationMs > 500).length;
  const errorCount = snapshot.errors.length;

  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Endpoints tracked | ${snapshot.backendMetrics.length} |`);
  lines.push(`| Slow endpoints (>500ms) | ${slowCount} |`);
  lines.push(`| Errors | ${errorCount} |`);
  lines.push(`| DB queries tracked | ${snapshot.dbMetrics.length} |`);
  lines.push(``);

  if (snapshot.recommendations.length > 0) {
    lines.push(`### Top Recommendation`);
    const top = snapshot.recommendations.sort((a, b) => a.priority - b.priority)[0];
    if (top) lines.push(`> ${top.action} — ${top.expectedImpact}`);
  }

  return lines.join('\n');
}
